apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: "httpbin-ns-teste-3"
 namespace: "ns-teste-3"
spec:
 host: "httpbin.ns-teste-3.svc.cluster.local"
 trafficPolicy:
   tls:
     mode: DISABLE