apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: policy
 namespace: default
spec:
 rules:
 # omitted

# apiVersion: authentication.istio.io/v1alpha1
# kind: Policy
# metadata:
#   name: default
#   namespace: frod
# spec:
#   peers:
#   - mtls: